automatic_grading_ftn/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.models import User, Group, Permission

from rest_framework import viewsets, routers
from webservice.models import Department, Course,  \
        Task, TaskFile, CourseSession, StudentEnrollment, \
        SubmitRequest, StudentAnswerFile, StudentAnswerTestResult, StudentAnswer

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#static models
class DepartmentViewSet(viewsets.ModelViewSet):
    model = Department
class CourseViewSet(viewsets.ModelViewSet):
    model = Course
class UserViewSet(viewsets.ModelViewSet):
    model = User            
class PermissionViewSet(viewsets.ModelViewSet):
    model = Permission           
class GroupViewSet(viewsets.ModelViewSet):
    model = Group            
#semester dynamic models
class CourseSessionViewSet(viewsets.ModelViewSet):
    model = CourseSession
class StudentEnrollmentViewSet(viewsets.ModelViewSet):
    model = StudentEnrollment
class TaskViewSet(viewsets.ModelViewSet):
    model = Task
class TaskFileViewSet(viewsets.ModelViewSet):
    model = TaskFile
#course dynamic models
class SubmitRequestViewSet(viewsets.ModelViewSet):
    model = SubmitRequest
class StudentAnswerViewSet(viewsets.ModelViewSet):
    model = StudentAnswer
class StudentAnswerTestResultViewSet(viewsets.ModelViewSet):
    model = StudentAnswerTestResult
class StudentAnswerFileViewSet(viewsets.ModelViewSet):
    model = StudentAnswerFile

router = routers.DefaultRouter()
router.register(r'rest/departments', DepartmentViewSet)
router.register(r'rest/courses', CourseViewSet)
router.register(r'rest/users', UserViewSet)
router.register(r'rest/permissions', PermissionViewSet)
router.register(r'rest/groups', GroupViewSet)

router.register(r'rest/courseSessions', CourseSessionViewSet)
router.register(r'rest/studentEnrollments', StudentEnrollmentViewSet)
router.register(r'rest/tasks', TaskViewSet)
router.register(r'rest/taskFiles', TaskFileViewSet)

router.register(r'rest/submitRequests', SubmitRequestViewSet)
router.register(r'rest/studentAnswers', StudentAnswerViewSet)
router.register(r'rest/studentAnswerTestResults', StudentAnswerTestResultViewSet)
router.register(r'rest/studentAnswerFiles', StudentAnswerFileViewSet)

urlpatterns = patterns('',
    url(r'^$', 'webservice.views.course.index'),
    url(r'^', include(router.urls)),

#not used atm
# url(r'^oauth2/', include('provider.oauth2.urls', namespace = 'oauth2')),
    url(r'^lti_launch',  'webservice.views.lti.lti_launch'),

    (r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^login$',  'webservice.views.auth.login'),
    url(r'^activate$',  'webservice.views.auth.activate'),
    url(r'^logout$', 'webservice.views.auth.logout'),

    url(r'^courses/$',                       'webservice.views.course.index'),
    url(r'^courses/create/$',                'webservice.views.course.create'),
    url(r'^courses/(?P<id>\d+)/$',           'webservice.views.course.read'),
    url(r'^courses/update/(?P<id>\d+)/$',    'webservice.views.course.update'),
    url(r'^courses/delete/(?P<id>\d+)/$',    'webservice.views.course.delete'),

    url(r'^course/(?P<courseSessionId>\d+)/addTask/$',  'webservice.views.task.create'),
    url(r'^task/(?P<id>\d+)/$',                         'webservice.views.task.read'),
    url(r'^task/(?P<id>\d+)/files/(?P<fileName>[^/]+)', 'webservice.views.task.fileDownload'),
    url(r'^task/update/(?P<id>\d+)/$',                  'webservice.views.task.update'),
    url(r'^task/delete/(?P<id>\d+)/$',                  'webservice.views.task.delete'),
    url(r'^task/(?P<id>\d+)/submitAnswer/$',            'webservice.views.task.submitAnswer'),

    url(r'^submit_answer/', 'webservice.views.custom.submit_answer'),
    # Uncomment the next line to enable the admin:
    url(r'^rest/create_user/', 'webservice.views.custom.create_user'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

webservice/models.py
from datetime import datetime
from functools import partial
import os
import os.path

from django.db import models
from django.contrib.auth.models import User

def renameUploadedFile(className, dir, instance, fileName):
    if not instance.id:
        instance.save()
    return os.sep.join([className, dir, str(instance.id) + os.path.splitext(fileName)[1]])

def groupFilesForSubmitAnswer(className, dir, instance, fileName):
    parentFolder = os.sep.join([className, dir, str(instance.studentAnswer.id)])
    return os.sep.join([parentFolder, fileName])

def groupFilesForTask(className, dir, instance, fileName):
    parentFolder = os.sep.join([className, dir, str(instance.task.id)])
    return os.sep.join([parentFolder, fileName])


class FileFormat(models.Model):
    name = models.CharField(max_length=100)
    extension = models.CharField(max_length=10)
    def __unicode__(self):
        return self.name + " " + self.extension

#mostly static
class Department(models.Model):
    name = models.CharField(max_length=200)
    shortName = models.CharField(max_length=10)
    description = models.CharField(max_length=10000, blank=True)
    def __unicode__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=200)
    shortName = models.CharField(max_length=10)
    description = models.CharField(max_length=10000, blank=True)
    department = models.ForeignKey(Department, null=True)
    def __unicode__(self):
        return self.name

class CourseFileFormat(models.Model):
    course = models.ForeignKey(Course, related_name="fileFormats")
    fileFormat = models.ForeignKey(FileFormat)
    def __unicode__(self):
        return self.course + " : " + self.fileFormat

#dynamic semester (frequency)
class CourseSession(models.Model):
    startDate = models.DateField(default=datetime.now, blank=True)
    endDate = models.DateField(null=True, blank=True)
    finished = models.BooleanField(default=False, blank=True)
    course = models.ForeignKey(Course)
    def __unicode__(self):
        return self.course.name + " " + unicode(self.startDate)

class CourseSessionTeacher(models.Model):
    courseSession = models.ForeignKey(CourseSession)
    user = models.ForeignKey(User)
    def __unicode__(self):
        return unicode(self.user) + " @ " + unicode(self.courseSession)

class StudentEnrollment(models.Model):
    startDate = models.DateField(default=datetime.now, blank=True)
    student = models.ForeignKey(User)
    courseSession = models.ForeignKey(CourseSession)
    finished = models.BooleanField(default=False, blank=True)
    def __unicode__(self):
        return unicode(self.courseSession) + ": " + unicode(self.student)

class Task(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=10000)
    public = models.BooleanField(default=True, blank=True)
    courseSession = models.ForeignKey(CourseSession)
    def __unicode__(self):
        if self.public:
            return self.name
        else:
            return self.name + " (not public) "

class TaskFile(models.Model):
    task = models.ForeignKey(Task)
    taskFile = models.FileField(blank=False, null=False, upload_to=partial(groupFilesForTask, "task_file", "task_file"))
    fileFormat = models.ForeignKey(FileFormat, null=True)
    
    T_TEST = 1
    T_IMPLEMENTATION = 2
    TYPE_CHOICES = (
        (T_TEST, "Test"),
        (T_IMPLEMENTATION, "Implementation"),
    )
    fileType = models.IntegerField(choices=TYPE_CHOICES, null=True, blank=True)
    public = models.BooleanField(default=True, blank=True)
    def __unicode__(self):
        return unicode(self.task) + " " + unicode(self.taskFile.name) + " Test: " + unicode(self.fileType) + " Public: " + unicode(self.public)
    def filename(self):
        return os.path.basename(self.taskFile.name)

#course dynamic
class SubmitRequest(models.Model):
    zipFile = models.FileField(upload_to=partial(renameUploadedFile, "submit_request", "zip_file"))
    def __unicode__(self):
        return unicode(self.studentAnswer) + " " + unicode(self.zipFile.name)

class StudentAnswer(models.Model):
    task = models.ForeignKey(Task)
    student = models.ForeignKey(User)
    submitRequest = models.ForeignKey(SubmitRequest, blank=True, null=True)
    success = models.BooleanField(default=False, blank=True)
    def __unicode__(self):
        return unicode(self.student) + " " + unicode(self.task)

class StudentAnswerTestResult(models.Model):
    studentAnswer = models.ForeignKey(StudentAnswer)
    success = models.BooleanField()
    resultText = models.CharField(max_length=100000)
    def __unicode__(self):
        return unicode(self.studentAnswer) + " " + unicode(self.success)

class StudentAnswerFile(models.Model):
    studentAnswer = models.ForeignKey(StudentAnswer)
    answerFile = models.FileField(upload_to=partial(groupFilesForSubmitAnswer, "student_answer_file", "answer_file"))
    def __unicode__(self):
        return unicode(self.studentAnswer) + " " + unicode(self.answerFile.name)

#LTI models
class LTIUser(models.Model):
    lti_user_id = models.CharField(primary_key=True, max_length=100)
    user = models.ForeignKey(User)

class LTICourse(models.Model):
    context_id = models.CharField(primary_key=True, max_length=100)
    course = models.ForeignKey(Course)

webservice/views/course.py
from django.forms.models import modelformset_factory
from django.db.models import Max
from django.shortcuts import  render, redirect
from django.contrib.auth.models import User
from webservice.models import Course, CourseSession, CourseSessionTeacher, Task, StudentAnswer
from webservice.forms import CourseForm
from webservice.views.shared import getShared, userIsTeacher

def index(request):
    layout = request.GET.get('layout')
    courses = []
    for v in Course.objects.all():
        courses.append(v)
    return render(request,
                  'course/index.html',
                  {'courses': courses, 'layout': layout, 'shared':getShared(request)} )

def create(request):
    if not request.user.is_superuser:
        return redirect('webservice.views.course.index')
    layout = request.GET.get('layout', 'horizontal')
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('webservice.views.course.index')
    else:
        form = CourseForm() # An unbound form

    return render(request,
                  'course/create.html',
                  {'form':form, 'layout':layout, 'shared':getShared(request)})

def read(request, id):
    layout = request.GET.get('layout', 'vertical')
    if not Course.objects.filter(id=id).exists():
        return redirect('webservice.views.course.index')

    course = Course.objects.get(id=id)
    courseSessions = CourseSession.objects.filter(course=course, finished=False).order_by('startDate')
    currentCourseSession = courseSessions[0]

    isTeacher = userIsTeacher(request.user, currentCourseSession)
    tasks = Task.objects.filter(courseSession=currentCourseSession)
    if not isTeacher:
        tasks = tasks.filter(public = True)

    #TODO: this could be too slow, revise maybe?
    if request.user.is_authenticated():
        studentAnswers = StudentAnswer.objects.filter(student = request.user)
        for task in tasks:
            task.success = False
            task.attempt = False
            correctAnswers = studentAnswers.filter(task=task, success=True)
            if correctAnswers.count() > 0:
                task.success = True
                task.attempt = True
            else:
                falseAnswers = studentAnswers.filter(task=task, success=False)
                if falseAnswers.count() > 0:
                    task.attempt = True

    return render(request,
                  'course/read.html',
                  {'course':course, 'tasks':tasks, 'courseSessions':courseSessions, 
                   'currentCourseSession':currentCourseSession, 'isTeacher':isTeacher, 
                   'layout':layout, 'shared':getShared(request)})


def update(request, id):
    if not request.user.is_superuser:
        return redirect('webservice.views.course.index')
    layout = request.GET.get('layout')
    if not Course.objects.filter(id=id).exists():
        return redirect('webservice.views.course.index')

    course = Course.objects.get(id=id)
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES, instance=course)
        if form.is_valid():
            form.save()
            return redirect('webservice.views.course.index')
    else:
        form = CourseForm(instance=course) # An unbound form

    return render(request,
                  'course/update.html',
                  {'Course' : course, 'layout': layout, 'form': form, 'shared':getShared(request)} )

def delete(request, id):
    if not request.user.is_superuser:
        return redirect('webservice.views.course.index')
    layout = request.GET.get('layout')
    if not Course.objects.filter(id=id).exists():
        return redirect('webservice.views.course.index')

    course = Course.objects.get(id=id)
    course.delete()

    return redirect('webservice.views.course.index', { 'layout': layout })

webservice/views/lti.py
from django.shortcuts import  render, redirect
from django.utils.translation import ugettext as _

from django.views.decorators.csrf import csrf_exempt
from django.utils import translation

from django.contrib import messages
import django.contrib.auth as django_auth

from webservice.views.shared import getShared
from webservice.forms import LTILaunchForm
from webservice.models import LTIUser, LTICourse, User, Course, CourseSession, CourseSessionTeacher, StudentEnrollment

@csrf_exempt
def lti_launch(request):
    if request.method == 'POST':
        form = LTILaunchForm(request.POST)
        if form.is_valid():
            lti_message_type = form.cleaned_data['lti_message_type']
            lti_version = form.cleaned_data['lti_version']
            resource_link_id = form.cleaned_data['resource_link_id']

            #set locale
            try:
                locale = form.cleaned_data['launch_presentation_locale']
                #FIXME: isn't properly setting the user language
                translation.activate(locale) 
            except Excetion as e:
                print(e)
            
            #get course info
            try:
                context_id = form.cleaned_data["context_id"]                
                context_type = form.cleaned_data["context_type"]
                context_title = form.cleaned_data["context_title"]
                context_label = form.cleaned_data["context_label"]
                try:
                    ltiCourse = LTICourse.objects.get(context_id = context_id)
                    course = ltiCourse.course
                    courseSessions = CourseSession.objects.filter(course=course, finished=False).order_by('startDate')
                    courseSession = courseSessions[0]
                except:
                    course = Course(name = context_title, shortName = context_label)
                    course.save()
                    courseSession = CourseSession(course = course)
                    courseSession.save()
                    ltiCourse = LTICourse(context_id = context_id, course = course)
                    ltiCourse.save()
            except Exception as e:
                print(e)

            #get user info
            try:
                user_id = form.cleaned_data["user_id"]
                user_first_name = form.cleaned_data["lis_person_name_given"]
                user_last_name = form.cleaned_data["lis_person_name_family"]
                try:
                    ltiUser = LTIUser.objects.get(lti_user_id = user_id)
                    user = ltiUser.user
                except:
                    #FIXME: make sure the username isn't taken already
                    user = User.objects.create_user(username="lti_"+user_id, first_name=user_first_name, last_name=user_last_name)
                    user.save()
                    ltiUser = LTIUser(user = user, lti_user_id = user_id)
                    ltiUser.save()
                django_auth.logout(request)
                user = django_auth.authenticate(lti_user_id=user_id)
                django_auth.login(request, user)
                request.session['using_lti'] = True
            except Exception as e:
                print(e)
            
            #get user roles
            try:
                for role in form.cleaned_data["roles"].split(","):
                    if role.lower() == "instructor":
                        try:
                            teachers = CourseSessionTeacher.objects.filter(courseSession=courseSession)
                            teachers = [teacher.user for teacher in teachers]
                            if user not in teachers:
                                courseSessionTeacher = CourseSessionTeacher(courseSession=courseSession, user=user)
                                courseSessionTeacher.save()

                        except Exception as e:
                            print(e)
                    elif role.lower() == "learner":
                        try:
                            studentEnrollment = StudentEnrollment.objects.get(student=user, courseSession=courseSession)
                        except:
                            studentEnrollment = StudentEnrollment(student=user, courseSession=courseSession)
                            studentEnrollment.save()

            except Exception as e:
                print(e)

            if course:
                return redirect('webservice.views.course.read', course.id)
    return redirect('webservice.views.course.index')

webservice/templates/task/create.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}
{% load i18n %}

{% block title %}Add task{% endblock %}

{% block extra_head %}
{% load staticfiles %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script src="{% static "js/vendor/jquery.ui.widget.js" %}"></script>
<script src="{% static "js/jquery.iframe-transport.js" %}"></script>
<script src="{% static "js/jquery.fileupload.js" %}"></script>
<script src="http://malsup.github.com/jquery.form.js"></script>
<script>
$(function () {
    {% comment %} hack needed so .send gets triggered even if there are no files {% endcomment %}
    window.allFiles = new Object();
    window.allFiles[-1] = '';
    fileIdLast = -1;
    $('#fileupload').fileupload({
        dataType: 'json',
        done: function (e, data) {
            $("#submitBtn").prop('disabled', false);
            $("#loaderGif").hide();
            result = data.result;
            if (result.success) {
                $(location).attr('href', "{% url 'webservice.views.course.read' course.id %}");
            } else {                
                $.each(result.errors, function(i, val) {
                    id = val[0];
                    error = val[1][0];                    

                    $("#id_" + id).parent().parent().addClass("error");
                    $("#id_" + id).parent().append('<span class="help-inline error">' + error + '</span>');
                });
            }            
        },
        error: function(e, data) {
            $("#submitBtn").prop('disabled', false);
            $("#loaderGif").hide();
            //alert("error happened");
        },
        add: function (e, data) {
            $.each(data.files, function (index, file) {
                fileIdLast++;
                window.allFiles[fileIdLast] = file;
                var id = fileIdLast;

                var newFileDiv = '<tr id="tr'+ id +'">';

                newFileDiv    += '<input type="hidden" value="' + file.name + '" name="form-' + id + 'taskFile"/>';

                newFileDiv    += '<td>' + file.name + '<span id="removeFile' + id + '" class="btn btn-link btn-mini removeFile"> <i class="icon-remove-circle"/></span> </td>';

                newFileDiv    += '<td><select name="form-' + id + 'fileFormat">';
                {% for courseFileFormat in course.fileFormats.all %}
                    newFileDiv    += '<option value={{courseFileFormat.fileFormat.id}}>{{courseFileFormat.fileFormat.name}} </option>';
                {% endfor %}
                newFileDiv    += '<option value=-1>Unspecified</option>';
                newFileDiv    += '</select></td>';


                newFileDiv    += '<td><select id="form-' + id + 'fileType" name="form-' + id + 'fileType">';
                {% for id, name in fileTypes %}
                    newFileDiv    += '<option value={{id}}>{{name}}</option>';
                {% endfor %}
                newFileDiv    += '<option value=-1>Other</option>';
                newFileDiv    += '</select></td>';
                
                newFileDiv    += '<td><input type="checkbox" name="form-' + id + 'publicFile"/></td>';
                newFileDiv    += '</tr>';
                
                $("#taskFiles").append(newFileDiv);

                $("#removeFile"+id).on("click", function() {
                    delete window.allFiles[id];
                    $("#tr"+id).remove();
                });

                $('#form-' + id + 'fileType').change(function() {
                    if (this.value > 0) { //test or implementation
                        $('input[name=form-' + id + 'publicFile]').prop("checked", false);
                    } else {
                        $('input[name=form-' + id + 'publicFile]').prop("checked", true);
                    }
                });

                $(".table").show();
            });
        }
    });

    $("#submitBtn").click(function(e) {
        event.preventDefault();
        var filesArray = [];
        $.each(window.allFiles, function(key, value) {
            console.log(key, value)
            var index = filesArray.push(value) - 1;
            $('input[name=form-' + key + 'taskFile]').attr('name', 'form-' + index + 'taskFile');
            $('select[name=form-' + key + 'fileFormat]').attr('name', 'form-' + index + 'fileFormat');
            $('select[name=form-' + key + 'fileType]').attr('name', 'form-' + index + 'fileType');
            $('input[name=form-' + key + 'publicFile]').attr('name', 'form-' + index + 'publicFile');
        });
        $("#submitBtn").prop('disabled', true);
        $("span.error").remove();
        $(".error").removeClass("error");
        $("#loaderGif").show();
        $("#fileupload").fileupload('send', {files:filesArray});
    });
});
</script>

{% endblock %}

{% block content %}

<h3>{% trans 'Add task' %}</h3>
<form class="form" id="taskForm" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form|as_bootstrap }}
    
    <hr/>
    <h4>Files</h4>
    <span class="btn btn-success fileinput-button">
        <span>{% trans 'Add files' %}...</span>
        <input type="file" id="fileupload" name="files[]" data-url="{% url 'webservice.views.task.create' courseSession.id %}" multiple>
    </span>
    <table class="table" hidden>
        <thead>
            <tr>
                <th>{% trans 'Name' %}</th>
                <th>{% trans 'Format' %}</th>
                <th>{% trans 'Type' %}</th>
                <th>{% trans 'Public' %}</th>
            </tr>
        </thead>
        <tbody id="taskFiles">
        </tbody>
    </table>

    <hr/>
    <input type="button" id="submitBtn" class="text btn btn-primary" value="{% trans 'Submit' %}"/>
    <img id="loaderGif" hidden src="{% static "gif/ajax-loader.gif" %}"/>

</form>
{% endblock %}

webservice/templates/task/read.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}
{% load i18n %}

{% block title %}{{task.name}}{% endblock %}


{% block extra_head %}
{% load staticfiles %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script src="{% static "js/vendor/jquery.ui.widget.js" %}"></script>
<script src="{% static "js/jquery.iframe-transport.js" %}"></script>
<script src="{% static "js/jquery.fileupload.js" %}"></script>
<script src="http://malsup.github.com/jquery.form.js"></script>
<script>
$(function () {
    window.allFiles = new Object();
    fileIdLast = -1;
    $("#submitBtn").prop('disabled', true);

    $('#fileupload').fileupload({
        dataType: 'json',
        done: function (e, data) {
            $("#submitBtn").prop('disabled', false);
            $("#loaderGif").hide();
            result = data.result;
            if (result.success) {
                $("#resultDiv").show();

                $('tr[class*=result]').remove();
                if (result.result.success) {
                    cls = 'success';
                } else {
                    cls = 'error';
                }
                //$('#resultDiv').attr('class', cls);
                $.each(result.result.testResults, function(i, testResult) {
                    if (testResult.success) {
                        cls = 'success';
                    } else {
                        cls = 'error';
                    }
                    var resultTr = '<tr class="result ' + cls + '">';
                    resultTr    += '<td>' + (i + 1) + '</td>';
                    resultTr    += '<td>' + testResult.msg + '</td>';
                    resultTr    += '<td>' + testResult.success + '</td>';
                    resultTr    += '</tr>';
                    
                    $("#results").append(resultTr);
                });
            } else {
                $.each(result.errors, function(i, val) {
                    id = val[0];
                    error = val[1][0];                    

                    $("#id_" + id).parent().parent().addClass("error");
                    $("#id_" + id).parent().append('<span class="help-inline error">' + error + '</span>');
                });
            }            
        },
        error: function(e, data) {
            $("#submitBtn").prop('disabled', false);
            $("#loaderGif").hide();
            //alert("error happened");
        },
        add: function (e, data) {
            $.each(data.files, function (index, file) {
                fileIdLast++;
                window.allFiles[fileIdLast] = file;
                var id = fileIdLast;
                var newFileTr = '<tr id="tr'+ id +'">';
                newFileTr    += '<input type="hidden" value="' + file.name + '" name="form-' + id + 'answerFile"/>';
                newFileTr    += '<td>' + file.name + '<span id="removeFile' + id + '" class="btn btn-link btn-mini removeFile"> <i class="icon-remove-circle"/></span> </td>';            
                newFileTr    += '</tr>';
                
                $("#answerFiles").append(newFileTr);

                $("#removeFile"+id).on("click", function() {
                    delete window.allFiles[id];
                    $("#tr"+id).remove();

                    if ($.isEmptyObject(window.allFiles)) {
                        $("#submitBtn").prop('disabled', true);
                    }
                });

                $("#fileTable").show();
            });
            if (!$.isEmptyObject(window.allFiles)) {
                $("#submitBtn").prop('disabled', false);
            }
        }
    });

    $("#submitBtn").click(function(e) {
        event.preventDefault();
        var filesArray = [];
        $.each(window.allFiles, function(key, value) {
            console.log(key, value)
            var index = filesArray.push(value) - 1;
            $('input[name=form-' + key + 'answerFile]').attr('name', 'form-' + index + 'answerFile');
        });
        if (filesArray.length > 0) {
            $("#submitBtn").prop('disabled', true);
            $("#loaderGif").show();
            $("#fileupload").fileupload('send', {files:filesArray});
        }
    });
});
</script>

{% endblock %}
{% block content %}
<div class="well">
    <h3>{{task.name}}</h3>
    <p>{{task.description}}</p>
</div
>
{% if taskFiles %}
    <h4>{% trans 'Files' %}:</h4>
    <ul>
    {% for taskFile in taskFiles %}
        <li>
        <a href="{% url 'webservice.views.task.fileDownload' task.id taskFile.filename %}">{{taskFile.filename}} 
            {% if isTeacher %}
                {% if taskFile.fileType %}
                    ({{taskFile.get_fileType_display}}) 
                {% endif %}
                {% if not taskFile.public %}
                    ({% trans 'Hidden' %})
                {% endif %}
            {% endif %}</a>
        </li>
    {% endfor %}
    </ul>
{% endif %}

{% if enrolled %}
<h3>{% trans 'Submit answer' %}</h3>

<form class="form" id="answerForm" enctype="multipart/form-data">

    {% csrf_token %}
    <hr/>
    <span class="btn btn-success fileinput-button">
        <span>{% trans 'Add files' %}...</span>
        <input type="file" id="fileupload" name="files[]" data-url="{% url 'webservice.views.task.submitAnswer' task.id %}" multiple>
    </span>
    <table class="table" id="fileTable" hidden>
        <thead>
            <tr>
                <th>{% trans 'Name' %}</th>
            </tr>
        </thead>
        <tbody id="answerFiles">
        </tbody>
    </table>

    <hr/>
    <input value="{% trans 'Check' %}" type="button" id="submitBtn" class="btn btn-primary" />
    <img id="loaderGif" hidden src="{% static "gif/ajax-loader.gif" %}"/>
</form>

<div id="resultDiv" hidden>
    <hr/>
    <h4>{% trans 'Results' %}</h4>
    <table class="table" id="resultTable">
        <thead>
            <tr>
                <th>#</th>
                <th>{% trans 'Message' %}</th>
                <th>{% trans 'Success' %}</th>
            </tr>
        </thead>
        <tbody id="results">
        </tbody>
    </table>
</div> {% comment %} if not enrolled {% endcomment %}
{% elif user.is_authenticated  %}
<div class="alert">{% trans 'You must be enrolled in this course to submit solutions.' %}</div>
{% else %} 
<div class="alert">{% trans 'You must be logged in to submit solutions.' %}</div>
{% endif %}
{% endblock %}

webservice/templates/task/update.html
{% extends "base.html" %}

{% block title %}Edit task {{ task.name }}{% endblock %}

{% block content %}
<form action="{% url 'webservice.views.task.update' task.id %}" method="post"
    {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>
{% endblock %}